name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build deps
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install libgdal-dev gdal-bin build-essential curl pkg-config libclang-dev valgrind -y
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
